fix "push sp"
davidly/ntvdm pull request #12
Opened 2024-04-12 22:07 UTC by Arcnor

"PUSH SP" when issued via the `0xFF` instruction is incorrect, in the same way as my fix for `0x54` from yesterday.

However, I'm not in love with this fix, it's not "clean" so maybe you have a better idea, but besides that, this completely fixes the issue.

2024-04-12 22:30 UTC, davidly requested changes
This case should be memory only -- push sp is opcode 0x54. So this new code should never be executed, right?

2024-04-12 22:44 UTC, Arcnor commented
> This case should be memory only -- push sp is opcode 0x54. So this new code should never be executed, right?

`0xFF` is also `push <register>`, and `0xFF 0xF4` decodes to `push sp`. I'm not really sure when this happens or why, though, that'd be up to the compiler...

2024-04-12 22:48 UTC, davidly commented
> > This case should be memory only -- push sp is opcode 0x54. So this new code should never be executed, right?
> 
> `0xFF` is also `push <register>`, and `0xFF 0xF4` decodes to `push sp`. I'm not really sure when this happens or why, though, that'd be up to the compiler...

Got it. The Intel documentation says FF 6 is memory-only, So this must be undocumented behavior. I'm fine with this change but can you please add a comment that it's undocumented? I haven't seen an app that does. Thanks

2024-04-12 22:58 UTC, Arcnor commented
I'll add a comment then, but I just checked the 8086 manual and `FF` appears as register/memory, so it's definitely documented :). `FE` however is not documented except for `INC/DEC`, although it also says register/memory for it.

2024-04-12 23:10 UTC, Arcnor commented
Done!

2024-04-12 23:12 UTC, merged

2024-04-12 23:13 UTC, davidly commented
Great! The October 1979 doc is ambiguous. it downs r/m but also just MEM16 :)

FF 1111 1111 MOD110R/M (DISP-LO),(DISP-HI) PUSH MEM16

2024-04-12 23:14 UTC, Arcnor commented
Ah yeah, I take those explanations more as examples of how it can be coded, and normally check the matrix in the later pages instead. It's also better explained in later editions IIRC, but of course we're only interested in the 8086 here :).

2024-04-14 17:14 UTC, davidly commented
Thanks for pointing out the ProcessorTests repo! Over the weekend I got them all working including undocumented instructions. The only broken things are some segment-wrapping operations that never happen in real life.

2024-04-14 17:19 UTC, Arcnor commented
> Thanks for pointing out the ProcessorTests repo! Over the weekend I got them all working including undocumented instructions. The only broken things are some segment-wrapping operations that never happen in real life. 

Oh, that's awesome, I was doing the same 😁. Does that mean you added support for div/mul with exceptions? It was one of the main missing ones, and probably one that might have modified behavior.

2024-04-14 17:26 UTC, Arcnor commented
Ah yeah, just saw your commits, that's fantastic. You even fixed some of the wraparound, I also had code for that but like before it was not "elegant" so was working on getting a better PR.